from sngan_projection.miscs.random_samples import sample_continuous
from sngan_projection.miscs.random_samples import sample_categorical
from sngan_projection.miscs.random_samples import sample_from_categorical_distribution
